# Copyright 2019-2024 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

[[permission]]
identifier = "open-external"
description = "Allow opening external links from the webview."
commands.allow = ["open_external"]
